# Generated by Django 5.2 on 2025-04-30 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='description')),
                ('avatar', models.ImageField(blank=True, default='images/account_avatars/default.jpg', null=True, upload_to='images/account_avatars/')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='registration_date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
