# Generated by Django 5.2 on 2025-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='account_avatars/default.jpg', upload_to='account_avatars/'),
        ),
    ]
