# Generated by Django 5.2 on 2025-04-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_username_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='account_avatars/default.jpg', null=True, upload_to='media/images/account_avatars/'),
        ),
    ]
