# Generated by Django 5.2 on 2025-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='account_avatars/default.jpg', null=True, upload_to='account_avatars/'),
        ),
    ]
