# Generated by Django 5.2 on 2025-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='account_avatars/default.jpg', null=True, upload_to='images/account_avatars/'),
        ),
    ]
