# Generated by Django 5.2 on 2025-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='category title')),
                ('image', models.ImageField(upload_to='images/category_images/', verbose_name='category image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='category created time')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
    ]
