# Generated by Django 5.2 on 2025-04-30 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='product title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='product created time')),
                ('product_image', models.ImageField(upload_to='images/product_images', verbose_name='product image')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Available quantity')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
