# Generated by Django 5.2 on 2025-04-28 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/product_images', verbose_name='product image'),
            preserve_default=False,
        ),
    ]
